jk instead of esc
bernardo-bruning/godot-vim pull request #2
Opened 2023-06-21 19:40 UTC by sdsaati

Hi, I modified a bit your code, to use jk combination instead of Esc button to go from insert mode to normal mode
btw, Thank you for this amazing addon!

2023-09-29 02:01 UTC, bernardo-bruning requested changes
Hi @sdsaati thanks for contribute, after somes PRs your PR get some conflicts, can fix this?

2023-09-29 02:01 UTC, bernardo-bruning commented on addons/godot_vim/plugin.gd
> +				print("j is pressed")
Please remove this print

2023-09-29 02:01 UTC, bernardo-bruning commented on addons/godot_vim/plugin.gd
> +					print("k is pressed too")
Please remove this print

2023-09-29 04:51 UTC, sdsaati commented
Hi @bernardo-bruning, thank you for the response, I removed those prints and made a new commit, should I do anything else?

2023-09-29 19:21 UTC, bernardo-bruning commented
I see conflicts between my branch and yours, the repository has introduced hard changes in the last few days, and resolving conflicts needs to fix to apply your PR.

@sdsaati

2023-09-30 07:03 UTC, sdsaati commented
> I see conflicts between my branch and yours, the repository has introduced hard changes in the last few days, and resolving conflicts needs to fix to apply your PR.
> 
> @sdsaati

Thanks, I will try to solve the conflicts, please give me about 2 or 3 days, then I'll apply the results

2023-10-01 09:41 UTC, sdsaati commented
Hi, I think now there is no conflicts, this code adds 'jk' as an alternative to 'esc' in order to going to normal mode

2023-10-01 19:57 UTC, bernardo-bruning approved these changes
Great job! Thanks for contributing. 
I will release version 0.3 on Friday with your contribution.

2023-10-01 19:58 UTC, merged